In [74]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [52]:
# Load the Data
df = pd.read_csv("StudentPerformanceFactors.csv")

In [53]:
# First 5 rows
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [54]:
# Last 5 rows
df.tail()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [55]:
print("Shape of the Data: ")
print(df.shape)

Shape of the Data:
(6607, 20)

In [56]:
print("Summary of the dataset: ")
print(df.info())

Summary of the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 696.9+ KB
None

In [57]:
# Standardise the Column Names
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
)
print(df.columns)

Index(['hours_studied', 'attendance', 'parental_involvement',
       'access_to_resources', 'extracurricular_activities', 'sleep_hours',
       'previous_scores', 'motivation_level', 'internet_access',
       'tutoring_sessions', 'family_income', 'teacher_quality', 'school_type',
       'peer_influence', 'physical_activity', 'learning_disabilities',
       'parental_education_level', 'distance_from_home', 'gender',
       'exam_score'],
      dtype='object')

In [58]:
# Datatypes of Each Column
print("Datatypes of Each Column :")
print(df.dtypes)

Datatypes of Each Column :
hours_studied                  int64
attendance                     int64
parental_involvement          object
access_to_resources           object
extracurricular_activities    object
sleep_hours                    int64
previous_scores                int64
motivation_level              object
internet_access               object
tutoring_sessions              int64
family_income                 object
teacher_quality               object
school_type                   object
peer_influence                object
physical_activity              int64
learning_disabilities         object
parental_education_level      object
distance_from_home            object
gender                        object
exam_score                     int64
dtype: object

In [59]:
# Numerical Columns Statistical Summary
print("Statistic Summary for Numerical Columns:")
print(df.describe())

Statistic Summary for Numerical Columns:
       hours_studied   attendance  sleep_hours  previous_scores  \
count    6607.000000  6607.000000   6607.00000      6607.000000
mean       19.975329    79.977448      7.02906        75.070531
std         5.990594    11.547475      1.46812        14.399784
min         1.000000    60.000000      4.00000        50.000000
25%        16.000000    70.000000      6.00000        63.000000
50%        20.000000    80.000000      7.00000        75.000000
75%        24.000000    90.000000      8.00000        88.000000
max        44.000000   100.000000     10.00000       100.000000

       tutoring_sessions  physical_activity   exam_score
count        6607.000000        6607.000000  6607.000000
mean            1.493719           2.967610    67.235659
std             1.230570           1.031231     3.890456
min             0.000000           0.000000    55.000000
25%             1.000000           2.000000    65.000000
50%             1.000000           3.000000    67.000000
75%             2.000000           4.000000    69.000000
max             8.000000           6.000000   101.000000

In [60]:
# Missing Values check
missing_values = df.isnull().sum()
print("Missing Values for Each Column")
print(missing_values)

Missing Values for Each Column
hours_studied                  0
attendance                     0
parental_involvement           0
access_to_resources            0
extracurricular_activities     0
sleep_hours                    0
previous_scores                0
motivation_level               0
internet_access                0
tutoring_sessions              0
family_income                  0
teacher_quality               78
school_type                    0
peer_influence                 0
physical_activity              0
learning_disabilities          0
parental_education_level      90
distance_from_home            67
gender                         0
exam_score                     0
dtype: int64

In [61]:
# Duplicate values Check
duplicates = df.duplicated().sum()
print("Duplicate Row Count: ")
print(duplicates)

Duplicate Row Count:
0

In [62]:
# Handle Missing Values
df['teacher_quality'] = df['teacher_quality'].fillna('Unknown')
df['parental_education_level'] = df['parental_education_level'].fillna('Unknown')
df['distance_from_home'] = df['distance_from_home'].fillna('Unknown')

In [63]:
df.isnull().sum()

hours_studied                 0
attendance                    0
parental_involvement          0
access_to_resources           0
extracurricular_activities    0
sleep_hours                   0
previous_scores               0
motivation_level              0
internet_access               0
tutoring_sessions             0
family_income                 0
teacher_quality               0
school_type                   0
peer_influence                0
physical_activity             0
learning_disabilities         0
parental_education_level      0
distance_from_home            0
gender                        0
exam_score                    0
dtype: int64

In [64]:
# Encoding Columns
# Nominal Encoding
cat_cols = ['gender','school_type','peer_influence','internet_access']
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[cat_cols])
new_cols = encoder.get_feature_names_out(cat_cols)
# add encoded columns to df
df[new_cols] = encoded

In [65]:
df.head()

,hours_studied,attendance,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,previous_scores,motivation_level,internet_access,tutoring_sessions,...,exam_score,gender_Female,gender_Male,school_type_Private,school_type_Public,peer_influence_Negative,peer_influence_Neutral,peer_influence_Positive,internet_access_No,internet_access_Yes
0,23,84,Low,High,No,7,73,Low,Yes,0,...,67,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,61,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,74,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,71,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,70,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [66]:
# Ordinal Encoding
# Sort Values Orderwise (Low < Medium < High)
mapping = {'Low': 0 , 'Medium':1 , 'High': 2, 'Unknown': -1}
df['parental_involvement_encoded'] = df['parental_involvement'].map(mapping)
df['access_to_resources_encoded'] = df['access_to_resources'].map(mapping)
df['motivation_level_encoded'] = df['motivation_level'].map(mapping)
df['family_income_encoded'] = df['family_income'].map(mapping)
df['teacher_quality_encoded'] = df['teacher_quality'].map(mapping)

In [67]:
df.head()

,hours_studied,attendance,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,previous_scores,motivation_level,internet_access,tutoring_sessions,...,peer_influence_Negative,peer_influence_Neutral,peer_influence_Positive,internet_access_No,internet_access_Yes,parental_involvement_encoded,access_to_resources_encoded,motivation_level_encoded,family_income_encoded,teacher_quality_encoded
0,23,84,Low,High,No,7,73,Low,Yes,0,...,0.0,0.0,1.0,0.0,1.0,0,2,0,0,1
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,1.0,0.0,0.0,0.0,1.0,0,1,0,1,1
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,0.0,1.0,0.0,0.0,1.0,1,1,1,1,1
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,1.0,0.0,0.0,0.0,1.0,0,1,1,1,1
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,0.0,1.0,0.0,0.0,1.0,1,1,1,1,2

In [68]:
# Binning - Numerical to Categorial
# Converting numbers to Meaningful Groups
df['study_level'] = pd.cut(df['hours_studied'] , bins = [0, 10, 20 , 45], labels =['Low', 'Medium', 'High'])
df['attendance_level'] = pd.cut(df['attendance'] , bins = [0, 70, 85, 100], labels =['Poor', 'Average', 'Good'])
df['sleep_category'] = pd.cut(df['sleep_hours'] , bins = [0, 5, 7, 10], labels =['Low Sleep', 'Normal Sleep', 'Healthy Sleep'])
df.head()

,hours_studied,attendance,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,previous_scores,motivation_level,internet_access,tutoring_sessions,...,internet_access_No,internet_access_Yes,parental_involvement_encoded,access_to_resources_encoded,motivation_level_encoded,family_income_encoded,teacher_quality_encoded,study_level,attendance_level,sleep_category
0,23,84,Low,High,No,7,73,Low,Yes,0,...,0.0,1.0,0,2,0,0,1,High,Average,Normal Sleep
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,0.0,1.0,0,1,0,1,1,Medium,Poor,Healthy Sleep
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,0.0,1.0,1,1,1,1,1,High,Good,Normal Sleep
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,0.0,1.0,0,1,1,1,1,High,Good,Healthy Sleep
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,0.0,1.0,1,1,1,1,2,Medium,Good,Normal Sleep

In [69]:
# Scaling
scaler = StandardScaler()

scaled = scaler.fit_transform(df[['hours_studied', 'attendance', 'sleep_hours', 'previous_scores', 'tutoring_sessions']])
df[['hours_studied_scaled', 'attendance_scaled', 'sleep_hours_scaled','previous_scores_scaled', 'tutoring_sessions_scaled']] = scaled
df.head()

,hours_studied,attendance,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,previous_scores,motivation_level,internet_access,tutoring_sessions,...,family_income_encoded,teacher_quality_encoded,study_level,attendance_level,sleep_category,hours_studied_scaled,attendance_scaled,sleep_hours_scaled,previous_scores_scaled,tutoring_sessions_scaled
0,23,84,Low,High,No,7,73,Low,Yes,0,...,0,1,High,Average,Normal Sleep,0.504942,0.348375,-0.019796,-0.143800,-1.213934
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,1,1,Medium,Poor,Healthy Sleep,-0.162822,-1.383736,0.661399,-1.116110,0.411451
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,1,1,High,Good,Normal Sleep,0.671882,1.560853,-0.019796,1.106313,0.411451
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,1,1,High,Good,Healthy Sleep,1.506587,0.781403,0.661399,1.592469,-0.401242
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,1,2,Medium,Good,Normal Sleep,-0.162822,1.041220,-0.700990,-0.699406,1.224144

In [70]:
# Interactive Features
df['study_effort'] = df['hours_studied'] * df['attendance']
df['learning_efficiency'] = df['previous_scores'] * df['hours_studied']
df['activity_study_balance'] = df['physical_activity'] * df['hours_studied']
df['tutoring_study_impact'] = df['tutoring_sessions'] * df['hours_studied']

In [71]:
df.head()

,hours_studied,attendance,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,previous_scores,motivation_level,internet_access,tutoring_sessions,...,sleep_category,hours_studied_scaled,attendance_scaled,sleep_hours_scaled,previous_scores_scaled,tutoring_sessions_scaled,study_effort,learning_efficiency,activity_study_balance,tutoring_study_impact
0,23,84,Low,High,No,7,73,Low,Yes,0,...,Normal Sleep,0.504942,0.348375,-0.019796,-0.143800,-1.213934,1932,1679,69,0
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,Healthy Sleep,-0.162822,-1.383736,0.661399,-1.116110,0.411451,1216,1121,76,38
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,Normal Sleep,0.671882,1.560853,-0.019796,1.106313,0.411451,2352,2184,96,48
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,Healthy Sleep,1.506587,0.781403,0.661399,1.592469,-0.401242,2581,2842,116,29
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,Normal Sleep,-0.162822,1.041220,-0.700990,-0.699406,1.224144,1748,1235,76,57

In [72]:
print("Shape of the Data after creating Encoding , scaling , binning and intercative features: ")
print(df.shape)

Shape of the Data after creating Encoding , scaling , binning and intercative features:
(6607, 46)

In [73]:
df.to_csv('student_performance_features.csv', index=False)